services:
  chat-app:
    container_name: "chat-app"
    image: postgres:17-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_DB: ${DATASOURCE_DB}